import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'

const testDb = path.resolve('data/test-db.json')
process.env.DB_PATH = testDb
process.env.JWT_SECRET = 'test-secret'
process.env.NODE_ENV = 'test'
await fs.writeFile(testDb, JSON.stringify({ users: [], friendRequests: [], friendships: [], friendInvitations: [], groups: [], groupMembers: [], bringItems: [], expenses: [], expenseShares: [], settlements: [], activities: [], passwordResetTokens: [] }))
const { default: app } = await import('../src/app.js')
const server = app.listen(0)
const base = `http://127.0.0.1:${server.address().port}/api`

async function call(pathname, options = {}) {
  const response = await fetch(`${base}${pathname}`, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    },
    body: options.body ? JSON.stringify(options.body) : undefined
  })
  return { status: response.status, data: await response.json() }
}

test('account to partial settlement flow stays correct', async t => {
  t.after(async () => {
    await new Promise(resolve => server.close(resolve))
    await fs.rm(testDb, { force: true })
  })

  const alice = await call('/auth/register', { method: 'POST', body: { name: 'Alice Green', username: 'alice', email: 'alice@example.com', password: 'password1', confirmPassword: 'password1' } })
  const bob = await call('/auth/register', { method: 'POST', body: { name: 'Bob Stone', username: 'bob', email: 'bob@example.com', password: 'password1', confirmPassword: 'password1' } })
  const carol = await call('/auth/register', { method: 'POST', body: { name: 'Carol Rose', username: 'carol', email: 'carol@example.com', password: 'password1', confirmPassword: 'password1' } })
  assert.equal(alice.status, 201)
  assert.equal(bob.status, 201)
  assert.equal(carol.status, 201)
  const aliceAuth = { Authorization: `Bearer ${alice.data.token}` }
  const bobAuth = { Authorization: `Bearer ${bob.data.token}` }
  const carolAuth = { Authorization: `Bearer ${carol.data.token}` }

  const friendInvite = await call('/friends/invite-link', { headers: aliceAuth })
  assert.equal(friendInvite.status, 200)
  assert.equal(friendInvite.data.code.length, 32)
  const friendPreview = await call(`/friends/invitations/${friendInvite.data.code}`)
  assert.equal(friendPreview.status, 200)
  assert.equal(friendPreview.data.inviter.id, alice.data.user.id)
  const selfFriendInvite = await call(`/friends/invitations/${friendInvite.data.code}/accept`, { method: 'POST', headers: aliceAuth, body: {} })
  assert.equal(selfFriendInvite.status, 400)
  const acceptedFriendInvite = await call(`/friends/invitations/${friendInvite.data.code}/accept`, { method: 'POST', headers: carolAuth, body: {} })
  assert.equal(acceptedFriendInvite.status, 200)
  assert.equal(acceptedFriendInvite.data.alreadyFriends, false)
  const repeatedFriendInvite = await call(`/friends/invitations/${friendInvite.data.code}/accept`, { method: 'POST', headers: carolAuth, body: {} })
  assert.equal(repeatedFriendInvite.status, 200)
  assert.equal(repeatedFriendInvite.data.alreadyFriends, true)
  const carolFriends = await call('/friends', { headers: carolAuth })
  assert.equal(carolFriends.data.friends.some(item => item.id === alice.data.user.id), true)

  const request = await call('/friends/requests', { method: 'POST', headers: aliceAuth, body: { receiverId: bob.data.user.id } })
  assert.equal(request.status, 201)
  const duplicate = await call('/friends/requests', { method: 'POST', headers: aliceAuth, body: { receiverId: bob.data.user.id } })
  assert.equal(duplicate.status, 409)
  const incoming = await call('/friends', { headers: bobAuth })
  await call(`/friends/requests/${incoming.data.requests[0].id}`, { method: 'PATCH', headers: bobAuth, body: { status: 'accepted' } })

  const created = await call('/groups', { method: 'POST', headers: aliceAuth, body: { name: 'Test trip', description: 'A tested group', currency: 'USD', friendIds: JSON.stringify([bob.data.user.id]) } })
  assert.equal(created.status, 201)
  const groupId = created.data.group.id
  const groupInvitePreview = await call(`/invitations/${created.data.group.invitationCode}`)
  assert.equal(groupInvitePreview.status, 200)
  assert.equal(groupInvitePreview.data.group.id, groupId)
  const groupInviteJoin = await call(`/invitations/${created.data.group.invitationCode}/join`, { method: 'POST', headers: carolAuth, body: {} })
  assert.equal(groupInviteJoin.status, 200)
  assert.equal(groupInviteJoin.data.groupId, groupId)
  const repeatedGroupInviteJoin = await call(`/invitations/${created.data.group.invitationCode}/join`, { method: 'POST', headers: carolAuth, body: {} })
  assert.equal(repeatedGroupInviteJoin.status, 200)
  const joinedGroup = await call(`/groups/${groupId}`, { headers: carolAuth })
  assert.equal(joinedGroup.status, 200)
  assert.equal(joinedGroup.data.group.members.filter(item => item.userId === carol.data.user.id).length, 1)
  const memberInviteRegenerate = await call(`/groups/${groupId}/invitation/regenerate`, { method: 'POST', headers: bobAuth, body: {} })
  assert.equal(memberInviteRegenerate.status, 200)
  const memberInviteDisable = await call(`/groups/${groupId}/invitation/disable`, { method: 'POST', headers: carolAuth, body: {} })
  assert.equal(memberInviteDisable.status, 200)
  const enabledInviteAgain = await call(`/groups/${groupId}/invitation/regenerate`, { method: 'POST', headers: bobAuth, body: {} })
  assert.equal(enabledInviteAgain.status, 200)
  const memberAdminTransfer = await call(`/groups/${groupId}/admin`, { method: 'PATCH', headers: bobAuth, body: { userId: bob.data.user.id } })
  assert.equal(memberAdminTransfer.status, 200)
  const groupAfterAdminTransfer = await call(`/groups/${groupId}`, { headers: bobAuth })
  assert.equal(groupAfterAdminTransfer.data.group.adminId, bob.data.user.id)
  assert.equal(groupAfterAdminTransfer.data.group.ownerId, alice.data.user.id)
  const expense = await call(`/groups/${groupId}/expenses`, { method: 'POST', headers: aliceAuth, body: { title: 'Dinner', amount: 120, paidBy: alice.data.user.id, date: '2026-08-20', splitType: 'equal', participants: [alice.data.user.id, bob.data.user.id] } })
  assert.equal(expense.status, 201)
  const afterExpense = await call(`/groups/${groupId}`, { headers: aliceAuth })
  assert.equal(afterExpense.data.balances[0].debtorId, bob.data.user.id)
  assert.equal(afterExpense.data.balances[0].amount, 60)

  const memberExpense = await call(`/groups/${groupId}/expenses`, { method: 'POST', headers: aliceAuth, body: { title: 'Personal receipt', amount: 10, paidBy: alice.data.user.id, date: '2026-08-20', splitType: 'equal', participants: [alice.data.user.id] } })
  const memberExpenseDelete = await call(`/groups/${groupId}/expenses/${memberExpense.data.expense.id}`, { method: 'DELETE', headers: carolAuth })
  assert.equal(memberExpenseDelete.status, 200)
  const payment = await call(`/groups/${groupId}/settlements`, { method: 'POST', headers: carolAuth, body: { payerId: bob.data.user.id, receiverId: alice.data.user.id, amount: 40, date: '2026-08-20', note: 'Bank transfer' } })
  assert.equal(payment.status, 201)
  const afterPayment = await call(`/groups/${groupId}`, { headers: bobAuth })
  assert.equal(afterPayment.data.balances[0].amount, 20)
  assert.equal(afterPayment.data.settlements[0].amount, 40)
  const tooMuch = await call(`/groups/${groupId}/settlements`, { method: 'POST', headers: bobAuth, body: { payerId: bob.data.user.id, receiverId: alice.data.user.id, amount: 21 } })
  assert.equal(tooMuch.status, 400)
  const editedPercentage = await call(`/groups/${groupId}/expenses/${expense.data.expense.id}`, { method: 'PUT', headers: carolAuth, body: { title: 'Dinner', description: '', amount: 120, paidBy: alice.data.user.id, date: '2026-08-20', splitType: 'percentage', participants: [{ userId: alice.data.user.id, percentage: 25 }, { userId: bob.data.user.id, percentage: 75 }] } })
  assert.equal(editedPercentage.status, 200)
  const afterPercentageEdit = await call(`/groups/${groupId}`, { headers: aliceAuth })
  const editedExpense = afterPercentageEdit.data.expenses.find(item => item.id === expense.data.expense.id)
  assert.equal(editedExpense.splitType, 'percentage')
  assert.equal(editedExpense.shares.find(item => item.userId === alice.data.user.id).percentage, 25)
  assert.equal(editedExpense.shares.find(item => item.userId === bob.data.user.id).percentage, 75)
  assert.equal(afterPercentageEdit.data.balances[0].amount, 50)

  const memberSettlementEdit = await call(`/groups/${groupId}/settlements/${payment.data.settlement.id}`, { method: 'PUT', headers: carolAuth, body: { payerId: bob.data.user.id, receiverId: alice.data.user.id, amount: 45, date: '2026-08-21', note: 'Member edit' } })
  assert.equal(memberSettlementEdit.status, 200)
  const settlementEdit = await call(`/groups/${groupId}/settlements/${payment.data.settlement.id}`, { method: 'PUT', headers: bobAuth, body: { payerId: bob.data.user.id, receiverId: alice.data.user.id, amount: 50, date: '2026-08-21', note: 'Edited transfer' } })
  assert.equal(settlementEdit.status, 200)
  assert.equal(settlementEdit.data.settlement.amountCents, 5000)
  assert.equal(settlementEdit.data.settlement.note, 'Edited transfer')
  const afterSettlementEdit = await call(`/groups/${groupId}`, { headers: bobAuth })
  assert.equal(afterSettlementEdit.data.balances[0].amount, 40)
  assert.equal(afterSettlementEdit.data.settlements[0].amount, 50)
  assert.equal(afterSettlementEdit.data.settlements[0].settlementDate, '2026-08-21')
  const anonymousSettlements = await call('/settlements')
  assert.equal(anonymousSettlements.status, 401)
  const globalSettlements = await call('/settlements', { headers: bobAuth })
  assert.equal(globalSettlements.status, 200)
  assert.equal(globalSettlements.data.settlements[0].id, payment.data.settlement.id)
  assert.equal(globalSettlements.data.settlements[0].group.id, groupId)
  assert.equal(globalSettlements.data.settlements[0].payer.id, bob.data.user.id)
  assert.equal(globalSettlements.data.settlements[0].amount, 50)
  const memberSettlements = await call('/settlements', { headers: carolAuth })
  assert.equal(memberSettlements.data.settlements.length, 1)
  const excessiveSettlementEdit = await call(`/groups/${groupId}/settlements/${payment.data.settlement.id}`, { method: 'PUT', headers: bobAuth, body: { payerId: bob.data.user.id, receiverId: alice.data.user.id, amount: 91, date: '2026-08-21', note: '' } })
  assert.equal(excessiveSettlementEdit.status, 400)

  const invalidBringItem = await call(`/groups/${groupId}/bring-items`, { method: 'POST', headers: aliceAuth, body: { title: 'Ice', assignedTo: 'missing-user' } })
  assert.equal(invalidBringItem.status, 400)
  const bringItem = await call(`/groups/${groupId}/bring-items`, { method: 'POST', headers: aliceAuth, body: { title: 'Ice', assignedTo: carol.data.user.id } })
  assert.equal(bringItem.status, 201)
  assert.equal(bringItem.data.item.assignedUser.id, carol.data.user.id)
  const bringList = await call(`/groups/${groupId}/bring-items`, { headers: carolAuth })
  assert.equal(bringList.status, 200)
  assert.equal(bringList.data.items[0].title, 'Ice')
  const completedBringItem = await call(`/groups/${groupId}/bring-items/${bringItem.data.item.id}`, { method: 'PATCH', headers: bobAuth, body: { done: true } })
  assert.equal(completedBringItem.status, 200)
  assert.equal(completedBringItem.data.item.done, true)
  const memberBringDelete = await call(`/groups/${groupId}/bring-items/${bringItem.data.item.id}`, { method: 'DELETE', headers: bobAuth })
  assert.equal(memberBringDelete.status, 200)
  const persistentBringItem = await call(`/groups/${groupId}/bring-items`, { method: 'POST', headers: aliceAuth, body: { title: 'Plates', assignedTo: bob.data.user.id } })
  assert.equal(persistentBringItem.status, 201)
  const removableBringItem = await call(`/groups/${groupId}/bring-items`, { method: 'POST', headers: carolAuth, body: { title: 'Cups', assignedTo: bob.data.user.id } })
  const removedBringItem = await call(`/groups/${groupId}/bring-items/${removableBringItem.data.item.id}`, { method: 'DELETE', headers: carolAuth })
  assert.equal(removedBringItem.status, 200)
  const blockedManagerRemoval = await call(`/groups/${groupId}/members/${alice.data.user.id}`, { method: 'DELETE', headers: bobAuth })
  assert.equal(blockedManagerRemoval.status, 400)
  const memberRemoval = await call(`/groups/${groupId}/members/${carol.data.user.id}`, { method: 'DELETE', headers: bobAuth })
  assert.equal(memberRemoval.status, 200)

  const unknownRecovery = await call('/auth/forgot-password', { method: 'POST', body: { email: 'nobody@example.com' } })
  assert.equal(unknownRecovery.status, 200)
  assert.equal(unknownRecovery.data.resetToken, undefined)
  const recovery = await call('/auth/forgot-password', { method: 'POST', body: { email: 'alice@example.com' } })
  assert.equal(recovery.status, 200)
  assert.ok(recovery.data.resetToken)
  const invalidReset = await call('/auth/reset-password', { method: 'POST', body: { token: 'invalid', password: 'newpassword1', confirmPassword: 'newpassword1' } })
  assert.equal(invalidReset.status, 400)
  const reset = await call('/auth/reset-password', { method: 'POST', body: { token: recovery.data.resetToken, password: 'newpassword1', confirmPassword: 'newpassword1' } })
  assert.equal(reset.status, 200)
  const oldSession = await call('/auth/me', { headers: aliceAuth })
  assert.equal(oldSession.status, 401)
  const oldLogin = await call('/auth/login', { method: 'POST', body: { login: 'alice@example.com', password: 'password1' } })
  assert.equal(oldLogin.status, 401)
  const newLogin = await call('/auth/login', { method: 'POST', body: { login: 'alice@example.com', password: 'newpassword1' } })
  assert.equal(newLogin.status, 200)
  const reusedReset = await call('/auth/reset-password', { method: 'POST', body: { token: recovery.data.resetToken, password: 'anotherpass1', confirmPassword: 'anotherpass1' } })
  assert.equal(reusedReset.status, 400)
  const blockedDelete = await call(`/groups/${groupId}`, { method: 'DELETE', headers: bobAuth })
  assert.equal(blockedDelete.status, 403)
  const deleted = await call(`/groups/${groupId}`, { method: 'DELETE', headers: { Authorization: `Bearer ${newLogin.data.token}` } })
  assert.equal(deleted.status, 200)
  const bobGroups = await call('/groups', { headers: bobAuth })
  assert.equal(bobGroups.data.groups.some(item => item.id === groupId), false)
  const carolGroups = await call('/groups', { headers: carolAuth })
  assert.equal(carolGroups.data.groups.some(item => item.id === groupId), false)
  const settlementsAfterDelete = await call('/settlements', { headers: bobAuth })
  assert.equal(settlementsAfterDelete.data.settlements.length, 0)
  const stored = JSON.parse(await fs.readFile(testDb, 'utf8'))
  assert.equal(stored.groups.some(item => item.id === groupId), false)
  assert.equal(stored.groupMembers.some(item => item.groupId === groupId), false)
  assert.equal(stored.expenses.some(item => item.groupId === groupId), false)
  assert.equal(stored.expenseShares.some(item => item.expenseId === expense.data.expense.id), false)
  assert.equal(stored.settlements.some(item => item.groupId === groupId), false)
  assert.equal(stored.bringItems.some(item => item.groupId === groupId), false)
  assert.equal(stored.activities.some(item => item.groupId === groupId), false)
  assert.equal(stored.friendInvitations.filter(item => item.userId === alice.data.user.id).length, 1)
  assert.equal(stored.friendships.filter(item => [item.user1Id, item.user2Id].includes(alice.data.user.id) && [item.user1Id, item.user2Id].includes(carol.data.user.id)).length, 1)
})
